image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - release

variables:
  # DOCKER_HOST: tcp://docker:2375
  # DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  # CI_REPOSITORY_URL: 'http://192.168.0.17:8012/scott/understory.git/'
  # CI_SERVER_URL: "http://192.168.0.17"
  # CI_SERVER_HOST="example.com"
  # CI_SERVER_PORT: "8012"

test:
  stage: test
  image: tiangolo/docker-with-compose
  script:
    - export
    - chmod +x ./setup_env.sh
    - sh ./setup_env.sh
    - docker-compose -f turtle.yml run --rm understory-staging python manage.py test -v 2
    - docker-compose -f turtle.yml build
    # - docker-compose -f turtle.yml run --rm understory-staging python manage.py collectstatic --no-input

# build:
#   stage: build
#   before_script:


