# Generated by Django 3.1.12 on 2021-09-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_questions', '0003_auto_20210525_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivequestionspage',
            name='is_flipbook',
            field=models.BooleanField(default=False),
        ),
    ]
