# Generated by Django 3.0.7 on 2020-06-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
