# Generated by Django 3.0.6 on 2020-06-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_issuepage_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuepage',
            old_name='issue',
            new_name='related_articles',
        ),
    ]
