# Generated by Django 3.0.6 on 2020-06-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20200612_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuepage',
            name='related_articles',
        ),
    ]
