# Generated by Django 3.0.6 on 2020-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200528_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('not_reviewed', 'Not reviewed'), ('review_in_progress', 'In progress'), ('review_complete', 'Review complete')], max_length=255, null=True),
        ),
    ]
