# Generated by Django 3.0.6 on 2020-05-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlesubmitpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('twitter', 'Twitter'), ('website', 'Website')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('not_reviewed', 'Not reviewed'), ('review_in_progress', 'In progress'), ('review_complete', 'Review complete')], default='not_reviewed', max_length=255),
        ),
    ]
