# Generated by Django 3.0.6 on 2020-05-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200529_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.CharField(choices=[('email', 'Email'), ('twitter', 'Twitter'), ('website', 'Website')], max_length=255, null=True),
        ),
    ]
