# Generated by Django 3.0.6 on 2020-05-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200529_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.CharField(blank=True, choices=[('name', 'Name'), ('email', 'Email'), ('twitter', 'Twitter'), ('website', 'Website')], default='name', max_length=255),
        ),
    ]
