# Generated by Django 3.0.6 on 2020-05-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200529_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='links',
        ),
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, choices=[('name', 'Name'), ('email', 'Email'), ('twitter', 'Twitter'), ('website', 'Website')], default='name', max_length=255, null=True),
        ),
    ]
