# Generated by Django 3.0.6 on 2020-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200529_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.CharField(choices=[('name', 'Name'), ('email', 'Email'), ('twitter', 'Twitter'), ('website', 'Website')], default='name', max_length=255, null=True),
        ),
    ]
