# Generated by Django 3.0.6 on 2020-05-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20200529_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='byline',
        ),
    ]
