# Generated by Django 3.0.6 on 2020-05-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_remove_article_byline'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.CharField(choices=[('name', 'Name'), ('email', 'Email'), ('twitter', 'Twitter'), ('website', 'Website')], default='name', max_length=255, null=True),
        ),
    ]
