# Generated by Django 3.0.6 on 2020-05-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_article_byline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='byline',
        ),
    ]
