# Generated by Django 3.0.6 on 2020-05-30 14:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_remove_article_byline'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesubmitpage',
            name='thank_you',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
