# Generated by Django 3.0.6 on 2020-05-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20200531_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='story_title',
        ),
    ]
