# Generated by Django 3.0.6 on 2020-05-31 17:57

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
        ('article', '0019_auto_20200531_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='issue',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issue.IssuePage'),
        ),
    ]
