# Generated by Django 3.0.6 on 2020-05-31 21:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_articlepage_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
