# Generated by Django 3.0.6 on 2020-05-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_articlepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
    ]
