# Generated by Django 3.0.6 on 2020-06-02 18:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('issue', '0001_initial'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('article', '0023_auto_20200531_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePageNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('status', models.CharField(choices=[('not_reviewed', 'Not reviewed'), ('review_in_progress', 'In progress'), ('review_complete', 'Review complete')], default='not_reviewed', max_length=255)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Post date')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issue.IssuePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='articletagpage',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='articletagpage',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ArticlePage',
        ),
        migrations.DeleteModel(
            name='ArticleTagPage',
        ),
    ]
