# Generated by Django 3.0.6 on 2020-06-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
        ('article', '0024_auto_20200602_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePageNew',
            new_name='ArticlePage',
        ),
    ]
