# Generated by Django 3.0.6 on 2020-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_auto_20200602_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='title',
            field=models.CharField(default='UGH', max_length=255),
            preserve_default=False,
        ),
    ]
