# Generated by Django 3.0.6 on 2020-06-02 19:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('article', '0027_articlepage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={},
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='title',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articletagpage',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='article.ArticlePage'),
        ),
    ]
