# Generated by Django 3.0.6 on 2020-09-07 19:46

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_auto_20200903_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='lead_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_text', wagtail.blocks.RichTextBlock()), ('embeded_item', wagtail.blocks.RawHTMLBlock())]),
        ),
    ]
