# Generated by Django 3.0.6 on 2020-06-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
        ('article', '0028_auto_20200602_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issue.IssuePage'),
        ),
    ]
