# Generated by Django 3.0.6 on 2020-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20200907_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='lead_image_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
