# Generated by Django 3.0.6 on 2020-06-02 20:05

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
        ('article', '0029_articlepage_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='issue',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issue.IssuePage'),
        ),
    ]
