# Generated by Django 3.0.6 on 2020-09-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0030_articlepage_lead_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='associated_english_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='article.ArticlePage'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
