# Generated by Django 3.1.7 on 2021-04-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0034_authororderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='website',
        ),
    ]
