# Generated by Django 3.1.7 on 2021-04-06 19:11

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('five_questions', '0001_initial'),
        ('invitations', '0001_initial'),
        ('article', '0043_auto_20210406_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivequestionsauthororderable',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='five_questions.fivequestionspage'),
        ),
        migrations.AlterField(
            model_name='invitationsauthororderable',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='invitations.invitationspage'),
        ),
    ]
