# Generated by Django 3.1.7 on 2021-04-06 19:11

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0044_auto_20210406_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authororderable',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='article.articlepage'),
        ),
    ]
