# Generated by Django 3.1.7 on 2021-04-15 16:52

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0045_auto_20210406_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='lead_image_text',
            new_name='lead_image_caption',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='lead_image_alt_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_two', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alt_text', wagtail.blocks.TextBlock()), ('caption_text', wagtail.blocks.RichTextBlock())], icon='image')), ('image_text', wagtail.blocks.RichTextBlock()), ('embeded_item', wagtail.blocks.RawHTMLBlock())]),
        ),
    ]
