# Generated by Django 3.1.7 on 2021-04-15 16:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0046_auto_20210415_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_with_alt_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alt_text', wagtail.blocks.TextBlock()), ('caption_text', wagtail.blocks.RichTextBlock())], icon='image')), ('image_text', wagtail.blocks.RichTextBlock()), ('embeded_item', wagtail.blocks.RawHTMLBlock())]),
        ),
    ]
