# Generated by Django 3.1.7 on 2021-04-24 10:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_remove_issuepage_related_articles'),
        ('article', '0048_auto_20210415_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='associated_English_article',
            field=models.ForeignKey(blank=True, help_text='If this article is not in English, and there exists an English translation of the article, select it here. This will enable automatic linking of the various translations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='article.articlepage'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_with_alt_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption_text', wagtail.blocks.RichTextBlock(required=False)), ('alt_text', wagtail.blocks.TextBlock(help_text='Specify the alt text to improve site accessibility. This should be  descriptive of the image and not merely a recitation of the caption text. Nor should it be duplicative of information in the caption. But it should be pithy. Perhaps no more than 125 characters. See best practices at https://axesslab.com/alt-texts/.')), ('formatting_options', wagtail.blocks.ChoiceBlock(choices=[('25_PERCENT_WIDTH', '25% width'), ('50_PERCENT_WIDTH', '50% width'), ('75_PERCENT_WIDTH', '75% width'), ('90_PERCENT_WIDTH', '90% width'), ('100_PERCENT_WIDTH', '100% width')], help_text='Select the formatting rules that apply this image. By default, images will span 100% of the width of the text column. Selecting 50% would render the image so that the width occupied 50% of the text column. Aspect ratios will be preserved. For a somewhat technical explanation of how images work in Wagtail, see https://docs.wagtail.io/en/v2.12.3/topics/images.html', required=False))], icon='image')), ('image_text', wagtail.blocks.RichTextBlock()), ('embeded_item', wagtail.blocks.RawHTMLBlock())]),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='This field is historical and not currently used. It may be removed in the future.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issue.issuepage'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='language',
            field=models.CharField(default='English', help_text='Specify the language in which the article is written. Note: the language must start with a capital letter.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='lead_image_alt_text',
            field=models.TextField(blank=True, help_text='Specify the alt text to improve site accessibility. This should be  descriptive of the image and not merely a recitation of the caption text. Nor should it be duplicative of information in the caption. But it should be pithy. Perhaps no more than 125 characters. See best practices at https://axesslab.com/alt-texts/.', null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='lead_image_formatting_options',
            field=models.CharField(choices=[('25_PERCENT_WIDTH', '25% width'), ('50_PERCENT_WIDTH', '50% width'), ('75_PERCENT_WIDTH', '75% width'), ('90_PERCENT_WIDTH', '90% width'), ('100_PERCENT_WIDTH', '100% width')], default='100_PERCENT_WIDTH', help_text='Select the formatting rules that apply this image. By default, images will span 100% of the width of the text column. Selecting 50% would render the image so that the width occupied 50% of the text column. Aspect ratios will be preserved. For a somewhat technical explanation of how images work in Wagtail, see https://docs.wagtail.io/en/v2.12.3/topics/images.html', max_length=255),
        ),
    ]
