# Generated by Django 4.0.4 on 2022-05-16 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0053_alter_articlepage_associated_english_article_and_more'),
        ('article', '0053_remove_articlepage_issue'),
    ]

    operations = [
    ]
