# Generated by Django 3.0.6 on 2020-06-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200609_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='blog_body',
            new_name='body',
        ),
    ]
