# Generated by Django 3.1.7 on 2021-03-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210328_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Privacy policy: text and slug', 'verbose_name_plural': 'Privacy policy: text and slug'},
        ),
        migrations.AlterModelOptions(
            name='termsofuse',
            options={'verbose_name': 'Terms of use: text and slug', 'verbose_name_plural': 'Terms of use: text and slug'},
        ),
    ]
