# Generated by Django 3.1.7 on 2021-03-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210328_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Click here to subscribe: text and slug', 'verbose_name_plural': 'Click here to subscribe: text and slug'},
        ),
    ]
