# Generated by Django 4.0.4 on 2022-05-16 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_alter_invitationspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationspage',
            name='associated_English_invitations',
            field=models.ForeignKey(blank=True, help_text='If this Invitation is not in English, and there exists an English translation of the Invitation, select it here. This will enable automatic linking of the various translations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='invitations.invitationspage'),
        ),
        migrations.AlterField(
            model_name='invitationspage',
            name='language',
            field=models.CharField(help_text='Specify the language in which the Invitation is written. Note: the language must start with a capital letter.', max_length=255),
        ),
    ]
