# Generated by Django 4.0.4 on 2022-05-30 19:56

import common.util.language_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_alter_invitationspage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationspage',
            old_name='associated_English_invitations',
            new_name='associated_English_article',
        ),
        migrations.AlterField(
            model_name='invitationspage',
            name='language',
            field=common.util.language_field.LanguageField(help_text='Specify the language in which the Invitation is written.', max_length=255),
        ),
    ]
