log:
  level: DEBUG

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

  #flower:
  #  address: ":5555"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "scottreidbarnes@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-router:
      rule: "Host(`us-test.fishcracker.net`)"
      
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    web-ojs-router:
      rule: "Host(`ojs-test.fishcracker.net`)"
      
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: ojs

    web-secure-router:
      rule: "Host(`us-test.fishcracker.net`)"
      
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    web-media-router:
      rule: "Host(`us-test.fishcracker.net`) && PathPrefix(`/media/`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

    web-secure-ojs-router:
      rule: "Host(`ojs-test.fishcracker.net`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: ojs
      tls:
        certResolver: letsencrypt

    #flower-secure-router:
    #  rule: "Host(`fishcracker.net`)"
    #  entryPoints:
    #    - flower
    #  service: flower
    #  tls:
    #    # https://docs.traefik.io/master/routing/routers/#certresolver
    #    certResolver: letsencrypt

  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:8000

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

    ojs:
      loadBalancer:
        servers:
          - url: http://172.31.34.26:8081
          # - url: http://172.31.34.26:8888  # local IP of the machine; 'localhost' goes to docker, not AWS.

    #flower:
    #  loadBalancer:
    #    servers:
    #      - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
