name: Understory CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

env:
  IMAGE: public.ecr.aws/i4c2l4g3/understory
  DJANGO_IMAGE: $IMAGE:django
  POSTGRESQL_IMAGE: $IMAGE:postgresql

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Understory image
        run: docker build . --file ./compose/production/Dockerfile --tag $IMAGE:DJANGO_IMAGE 
